# Generated by Django 4.2.10 on 2024-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product gallery', 'verbose_name_plural': 'Product gallery'},
        ),
    ]
